### ISSUE TITLE
Treinamento de modelagem de requisitos

### ISSUE THREAD

**Issue by Mateusas3s** [Mateusas3s/DS-Feudo-Violeta#23]
Existem várias técnicas de modelagem de requisitos de software. Uma delas é a Histórias de Usuário (tema da tarefa). O objetivo desta tarefa é:
- [ ] A dupla responsável estudar sobre o tema;
- [ ] Gravarem um vídeo entre 10 e 15 minuto explicando o tema
- [ ] Durante o vídeo explicarem o tema e criar um arquivo markdown sobre o tema, aplicando a técnica de pareamento. A dupla deve alternar quem edita o arquivo a cada 5 ou 10 minutos
- [ ] Publicarem o link nos comentários desta tarefa
- [ ] Aqueles que assistirem o video devem gravar a si mesmos o assistindo. Depois deve-se enviar o link para o Scrum Master no canal de comunicação rápida.

**Comment by Mateusas3s** [comment]
Sugestão de conteúdo:
- https://odonodoproduto.com/user-story-historia-de-usuario/

**Comment by uMorbeck** [comment]
Link para o vídeo sobre User Story:
https://www.youtube.com/watch?v=CXcZJzxZFSM

**Comment by Mateusas3s** [comment]
Wildemberg assistindo: https://unbbr.sharepoint.com/:v:/s/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoAzulEscuroVioleta/EelQBCpt9PJPmafL3ZMqzWQBHjzAKg1TDVCyu23tB6xdxw?e=U6sczc
